<div align="center">
    <h1>Matrix Manipulation</h1>
</div>

In [1]:
import numpy as np

## Add two matrices

In [2]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = np.array(X) + np.array(Y)
result

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Multiply two matrices

In [4]:
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

result = np.dot(A, B)
result

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [9]:
x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition: ")
print(np.add(x, y))
print()

print("Subtraction: ")
print(np.subtract(x, y))
print()

print("Division: ")
print(np.divide(x, y))
print()

print("Sum of column: ")
print(np.sum(y, axis=0))
print()

print("Sum of row: ")
print(np.sum(y, axis=1))
print()

print("Transpose matrix: ")
print(x.T)
print()

Addition: 
[[ 8 10]
 [13 15]]

Subtraction: 
[[-6 -6]
 [-5 -5]]

Division: 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]

Sum of column: 
[16 18]

Sum of row: 
[15 19]

Transpose matrix: 
[[1 4]
 [2 5]]



## Inverse Matrix

In [10]:
arr = np.array([[1, 2], [5, 6]])
print(np.linalg.inv(arr))

[[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [11]:
# Trace of a matrix
mat = [[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]]

print(np.trace(mat))

15


In [12]:
# Euclidean norm
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the Euclidean norm
print(np.linalg.norm(matrix))

16.881943016134134


In [13]:
# Frobenius norm
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the Euclidean norm
print(np.linalg.norm(matrix, ord='fro'))

16.881943016134134
