<div align="center">
    <h1>Numpy</h1>
</div>

In [1]:
import numpy as np

#### The Basics

In [8]:
a = np.array([1, 2, 3], dtype='int8')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get shape
b.shape

(2, 3)

In [9]:
# Get type
a.dtype

dtype('int8')

In [11]:
# Get total size
a.nbytes

3

#### Accessing / Changing specific element, rows, columns

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specifig element [row, column]
a[1, -2]

13

In [15]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specifig column
a[:, 2]

array([ 3, 10])

In [18]:
# Getting a little more fancy [start:end:step]
a[0, 1:6:2]

array([2, 4, 6])

#### 3-d example

In [20]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
# Get a specific element
b[0, 1, 1]

4

In [22]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

## Initializing Different Types of Arrays

In [26]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s matrix
np.ones((3, 2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [28]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [29]:
# Any other number
# np.full_like(a, 4)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.35117434, 0.30278399],
       [0.69045589, 0.86746228],
       [0.54846903, 0.79073285],
       [0.52762252, 0.80899545]])

In [31]:
np.random.random_sample(a.shape)

array([[0.35866883, 0.42836213, 0.7393113 , 0.77918612, 0.99344019,
        0.21228584, 0.40317085],
       [0.52244308, 0.94948684, 0.89467468, 0.75890332, 0.94645398,
        0.16064033, 0.35120995]])

In [35]:
# Random Integer values
np.random.randint(4, 7, size=(3, 3))

array([[4, 5, 5],
       [5, 6, 6],
       [4, 6, 5]])

In [36]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [44]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!

In [45]:
a = np.array([1, 2, 3])
b = a.copy()
b[1] = 99

print(a)
print(b)

[1 2 3]
[ 1 99  3]


## Mathematics

In [46]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [47]:
a + 2

array([3, 4, 5, 6])

In [48]:
a - 2

array([-1,  0,  1,  2])

## Linear Algebra

In [50]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

## Statistics

In [51]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.min(stats)

1

In [54]:
np.sum(stats)

21

In [55]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [57]:
## Reshape array
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [58]:
# vertically stacing vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Load data from File

In [62]:
fileData = np.genfromtxt('./data/numpy_data.txt', delimiter=',')
fileData = fileData.astype('int8')
fileData

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]], dtype=int8)

In [64]:
fileData[fileData > 10]

array([11, 12, 13, 14, 15, 16, 17, 18], dtype=int8)